name: Lineage OS GSI

on:
  workflow_dispatch:
jobs:
  test:
    name: Build GSIs using foss.crave.io

    runs-on: self-hosted

    steps:
    - name: Cleanup
      run: rm -rf *
    - name: Create workspace
      run: mkdir lineage-gsi
      continue-on-error: true
    - name: Enter Workspace
      run: cd lineage-gsi 
      continue-on-error: true
      # Check-out in order to access the repository's files.
    - name: Check-out to repository
      uses: actions/checkout@v4    
    - name: Test Local Manifests
      run: |
        repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --git-lfs
      #  git clone https://github.com/Veynamer/treble_manifest.git --depth 1 -b 14 .repo/local_manifests && \
        timeout 1m repo sync --force-sync || { exit_code=$?; [ $exit_code -eq 124 ] || (echo "Error: Process failed with exit code $exit_code"; exit $exit_code); }
        rm -rf .repo
      timeout-minutes: 10    
    - name: Exports
      run: |
        export BUILD_HOSTNAME=crave
        export BUILD_USERNAME=OkBuddyGSI
    - name: Run Script
      run: bash build.sh
      # Only reach this when the user killed the workflow.
    - name: Execute if the job is cancelled
      if: ${{ cancelled() }}
      run: crave stop --all
    - name: Find output file
      run: |
        mv */system.img LineageOS-21-Generic-$(date +%Y%m%d)-OkBuddyGSI-EXPERIMENTATIONS.img
        mv system.img LineageOS-21-Generic-$(date +%Y%m%d)-OkBuddyGSI-EXPERIMENTATIONS.img
        xz -z -k LineageOS*.img
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: | 
          *.img.xz
        name: LineageOS-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Target: LineageOS-21-Generic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
