name: Lineage OS GSI test

on:
  workflow_dispatch:

jobs:
  build-gsi:
    name: Build GSIs using GitHub-hosted runners
    runs-on: ubuntu-latest

    steps:
    - name: Cleanup
      run: rm -rf *

    - name: Create workspace
      run: mkdir lineage-gsi

    - name: Check-out repository
      uses: actions/checkout@v4

    - name: Set up environment variables
      run: |
        echo "BUILD_HOSTNAME=crave" >> $GITHUB_ENV
        echo "BUILD_USERNAME=OkBuddyGSI" >> $GITHUB_ENV

    - name: Run Script
      run: bash build.sh

    - name: Execute if the job is cancelled
      if: ${{ cancelled() }}
      run: echo "Build is cancelled."

    - name: Find and prepare the output file
      run: |
        mv */system.img LineageOS-21-Generic-$(date +%Y%m%d)-OkBuddyGSI-EXPERIMENTATIONS.img || true
        mv system.img LineageOS-21-Generic-$(date +%Y%m%d)-OkBuddyGSI-EXPERIMENTATIONS.img || true
        xz -z -k LineageOS*.img

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.img.xz
        name: LineageOS-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          This is the built LineageOS GSI.
          Target: LineageOS-21-Generic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
